baseurl = "https://blog.jumpingrivers.com/"
#baseurl = "https://tax-collector-jacinta-81460.netlify.com/"
title = "The Jumping Rivers Blog"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-uk"
# Enable comments by entering your Disqus shortname
disqusShortname = "blog-jumpingrivers"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-108053698-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
enableEmoji = true
rssLimit = 30
author = "Jumping Rivers"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Insights in data science and machine learning"
  copyright = "&copy;2018 Jumping Rivers Ltd"
  sidebarAbout = [
    "Jumping Rivers is a leading analytics company whose passion is data. We help our clients move from data storage to data insights.",
    "We provide both training and consultancy. Please get in contact!"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "info@jumpingrivers.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
#  facebook      = "full page or profile url in facebook"
#  googleplus    = "full profile url in googleplus"
  email         = "info@jumpingrivers.com"
  twitter       = "https://twitter.com/jumping_uk"
  linkedin      = "https://www.linkedin.com/company/21945868/"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
  github        = "https://github.com/jumpingrivers/"
  rss = "http://blog.jumpingrivers.com/index.xml"

